apiVersion: v1
entries:
  excalidash:
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Initial chart with single or split frontend/backend deployment modes.
    apiVersion: v2
    appVersion: 0.4.27
    created: "2026-04-26T15:25:50.116548+05:30"
    description: Production-oriented Helm chart for ExcaliDash with single or split
      frontend/backend deployment modes.
    digest: 6679fb8a8b10daae374cc55874f3570602ded57eb8393a8bbccbe4df022f5414
    home: https://github.com/ZimengXiong/ExcaliDash
    keywords:
    - excalidash
    - excalidraw
    - dashboard
    - collaboration
    - whiteboard
    kubeVersion: '>=1.25.0-0'
    maintainers:
    - name: Ashwini Jindal
    name: excalidash
    sources:
    - https://github.com/ZimengXiong/ExcaliDash
    - https://artifacthub.io/packages/helm/unxwares/excalidash
    type: application
    urls:
    - https://ashwinijindal10.github.io/excalidash-helm-repo/charts/excalidash-0.1.0.tgz
    version: 0.1.0
generated: "2026-04-26T15:25:50.112778+05:30"
