apiVersion: v1
entries:
  excalidash:
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Initial chart with single or split frontend/backend deployment modes.
        - kind: fixed
          description: Allow frontend and backend startup chown operations by default.
        - kind: fixed
          description: Exclude repository metadata and packaged artifacts from the Helm package.
    apiVersion: v2
    appVersion: 0.4.27
    created: "2026-04-26T15:39:08.078786+05:30"
    description: Production-oriented Helm chart for ExcaliDash with single or split
      frontend/backend deployment modes.
    digest: 50baa3daa0b5989860fac11b2c4728313fb24ba6d8fa56dbbe08e4fffe794b3c
    home: https://github.com/ZimengXiong/ExcaliDash
    keywords:
    - excalidash
    - excalidraw
    - dashboard
    - collaboration
    - whiteboard
    kubeVersion: '>=1.25.0-0'
    maintainers:
    - name: Ashwini Jindal
    name: excalidash
    sources:
    - https://github.com/ZimengXiong/ExcaliDash
    - https://artifacthub.io/packages/helm/unxwares/excalidash
    type: application
    urls:
    - https://ashwinijindal10.github.io/excalidash-helm-repo/charts/excalidash-0.1.4.tgz
    version: 0.1.4
  - annotations:
      artifacthub.io/changes: |
        - kind: added
          description: Initial chart with single or split frontend/backend deployment modes.
        - kind: fixed
          description: Allow frontend and backend startup chown operations by default.
    apiVersion: v2
    appVersion: 0.4.27
    created: "2026-04-26T15:39:08.077939+05:30"
    description: Production-oriented Helm chart for ExcaliDash with single or split
      frontend/backend deployment modes.
    digest: 2a0b6cdf0c30e4a73243daa793c314b09bf5150ef42b745a34aa4a588c759f5a
    home: https://github.com/ZimengXiong/ExcaliDash
    keywords:
    - excalidash
    - excalidraw
    - dashboard
    - collaboration
    - whiteboard
    kubeVersion: '>=1.25.0-0'
    maintainers:
    - name: Ashwini Jindal
    name: excalidash
    sources:
    - https://github.com/ZimengXiong/ExcaliDash
    - https://artifacthub.io/packages/helm/unxwares/excalidash
    type: application
    urls:
    - https://ashwinijindal10.github.io/excalidash-helm-repo/charts/excalidash-0.1.3.tgz
    version: 0.1.3
generated: "2026-04-26T15:39:08.066174+05:30"
