{{- if and .Values.backend.persistence.enabled (not .Values.backend.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "excalidash.backendPvcName" . }}
  labels:
    {{- include "excalidash.labels" . | nindent 4 }}
    {{- with .Values.backend.persistence.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.backend.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.backend.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
  {{- if .Values.backend.persistence.storageClass }}
  storageClassName: {{ .Values.backend.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
